[build]
  command = "npm run generate"  # Use 'nuxt generate' for static site generation
  publish = "dist"  # The folder where the built static files are generated
[[redirects]]
from = "/api/*"
to = "https://dicapta-strapi-app-production.up.railway.app/api/:splat"
status = 200